image: node:12.13.0

variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules

stages:
  - check
  - test
  - e2e
  - build
  - deploy

before_script:
  - yarn install

lint:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run lint

format:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run format:check

types:check:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run types:check

tests:unit:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run test:unit --silent --passWithNoTests

# .job_template:
#   image: cypress/browsers:node12.14.1-chrome83-ff77
#   stage: test
#   except:
#     - master
#     - tags
#   script:
#     - yarn cypress install
#     - yarn start-server-and-test "yarn develop" http://localhost:8000 "cypress run --browser chrome --record --parallel"
#   artifacts:
#     paths:
#       - cypress/videos
#       - cypress/screenshots

tests:smoke:
  image: cypress/browsers:node12.14.1-chrome83-ff77
  stage: test
  only:
    - master
  script:
    - yarn cypress install
    - yarn start-server-and-test "yarn develop" http://localhost:8000 "cypress run --config-file cypress-smoke.json --browser chrome"

tests:e2e:
  image: cypress/browsers:node12.14.1-chrome83-ff77
  stage: e2e
  only:
    - master
  script:
    - yarn cypress install
    - yarn start-server-and-test "yarn develop" http://localhost:8000 "cypress run --config-file cypress-e2e.json --browser chrome"

tests:visual:
  stage: e2e
  only:
    - master
  script:
    - echo "PERCY_TOKEN=${PERCY_TOKEN}" > .env
    - USE_PERCY=true yarn build

build:site:
  stage: build
  only:
    - master
  script:
    - touch .env
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
    - yarn run build
  artifacts:
    paths:
      - public

deploy:site:
  stage: deploy
  only:
    - master
  script:
    - npm i -g netlify-cli
    - yarn deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_PERSONAL_TOKEN --message "$CI_COMMIT_TITLE"
  dependencies:
    - build:site
