image: node:12.13.0

stages:
  - test

before_script:
  - yarn install

lint:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn format:check || true

format:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn format:check || true

types:check:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn types:check || true
