image: node:12.13.0

variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules

stages:
  - check
  - test
  - e2e
  - build
  - deploy

before_script:
  - yarn install

lint:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run lint

format:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run format:check

types:check:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run types:check

tests:unit:
  stage: check
  except:
    - master
    - tags
  script:
    - yarn run test:unit --silent

tests:smoke:
  stage: test
  image: cypress/browsers:node12.14.1-chrome83-ff77
  # only:
  #   - master
  script:
    - yarn cypress install
    - yarn start-server-and-test "yarn develop" http://localhost:8000 "cypress run --config-file cypress-smoke.json --browser chrome"

tests:e2e:
  image: cypress/browsers:node12.14.1-chrome83-ff77
  stage: e2e
  # only:
  #   - master
  script:
    - yarn cypress install
    - yarn start-server-and-test "yarn develop" http://localhost:8000 "cypress run --config-file cypress-e2e.json --browser chrome"

# tests:visual:
#   stage: e2e
#   image: buildkite/puppeteer
#   only:
#     - master
#   script:
#     - apt-get update && apt-get install git -y
#     - USE_PERCY=true yarn build

build:site:
  stage: build
  image: buildkite/puppeteer
  # only:
  #   - master
  script:
    - apt-get update && apt-get install git -y
    - yarn run build
  artifacts:
    paths:
      - public

deploy:site:
  stage: deploy
  only:
    - master
  script:
    - npm i netlify-cli
    - yarn deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_PERSONAL_TOKEN --message "$CI_COMMIT_TITLE"
  dependencies:
    - build:site
