image: node:12.13.0

variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install

lint:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn lint

format:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn format:check

types:check:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn types:check

tests:unit:
  stage: test
  except:
    - master
    - tags
  script:
    - yarn test:unit --silent --passWithNoTests

tests:smoke:
  image: cypress/browsers:node12.14.1-chrome83-ff77
  stage: test
  except:
    - master
    - tags
  script:
    - yarn cypress install
    - yarn test:e2e:smoke
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots

build:site:
  stage: build
  only:
    - master
  script:
    - echo "PERCY_TOKEN=${PERCY_TOKEN}" > .env
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
    - yarn run build
  artifacts:
    paths:
      - public

deploy:site:
  stage: deploy
  only:
    - master
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_PERSONAL_TOKEN --prod --message "$CI_COMMIT_TITLE" --dir public/
  dependencies:
    - build:site
